version: '2.2'
services:
  siren:
    image: tbfy/odc-tool:latest
    container_name: siren-container
    environment:
      SERVER_NAME: siren
      IDTENDER_SEARCH: ocds-0c46vo-0001-8233113a-28c7-4626-9c41-2f3cbfd7d1e6_ocds-b5fd17-df1f7eb0-89c0-4564-a474-ede9131fc40f-sch---7234
      TOTAL_DATOS_TENDER_SEARCH: 50
      TOTAL_DATOS_TENDER: 1000
      TOTAL_DATOS_AWARD: 1000
      TOTAL_DATOS_CONTRACTING_PROCESS: 1000
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9220:9220
      - 5606:5606
